spring:
  datasource:
    url: jdbc:sqlserver://sitetour-db-server.database.windows.net:1433;database=sitetour-db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: sitetouradmin
    password: Sitetour2024!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 8081